---
- name: "Changing the hostname"
  ansible.builtin.import_tasks: "roles/common/tasks/debian/os/hostname.yml"

- name: "Installing required packages"
  ansible.builtin.import_tasks: "installing-packages.yml"

- name: "Setting up the application"
  ansible.builtin.import_tasks: "setup-app.yml"

- name: "Enabling and setting up UFW"
  ansible.builtin.import_tasks: "ufw.yml"
