---
- name: "Ensure the '{{ docker_path }}' directory exists"
  ansible.builtin.file:
    path: "{{ docker_path }}"
    state: "directory"
    mode: "0644"

- name: "Copying the application's file to the target"
  ansible.builtin.copy:
    src: "docker/"
    dest: "{{ docker_path }}"
    mode: "0644"

- name: "Copying the application's SSL Certificate to the target"
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ certificates_dest_path }}"
    mode: "0644"
  loop: "{{ certificates }}"

- name: "Creating and starting services (docker-compose up)"
  community.docker.docker_compose_v2:
    project_name: "loadbalancer"
    project_src: "{{ docker_path }}"
    state: "present"
    restarted: true
  register: "output"
