---
- name: "Changing the hostname"
  ansible.builtin.import_tasks: "roles/common/tasks/debian/os/hostname.yml"

- name: "Installing required packages"
  ansible.builtin.import_tasks: "installing-packages.yml"

- name: "Removing unnecessary packages"
  ansible.builtin.import_tasks: "removing-packages.yml"

- name: "Recreating the machine-id file so the new VM can get a new IP"
  ansible.builtin.import_tasks: "roles/common/tasks/debian/os/machine-id.yml"

- name: "Removing unnecessary files, folders and configuration"
  ansible.builtin.import_tasks: "roles/common/tasks/debian/os/clean-up.yml"
